services:
  db:
    image: mysql:8
    container_name: ruja-crm-db
    restart: always
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - ruja-crm

  web:
    build: .
    container_name: ruja-crm-web
    restart: always
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ruja-crm

  nginx:
    image: nginx:latest
    container_name: ruja-crm-nginx
    restart: always
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - ruja-crm

networks:
  ruja-crm:

volumes:
  mysql_data:
  static_volume:
  media_volume: