# Generated by Django 5.2 on 2025-05-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleagas',
            options={'managed': True, 'verbose_name': 'Detalle de agente y aseguradora', 'verbose_name_plural': 'Detalles de agente y aseguradora'},
        ),
    ]
